version: '3.1'
services:
  mongo:
      image: 'mongo:latest'
      container_name: 'mongo'
      networks: 
       - "api.network"

  api: 
    build: 
      context: .
      dockerfile: Dockerfile
    image: devices-api
    ports: 
      - 8080
    deploy: 
      replicas: 3
    depends_on: 
      - 'mongo'
    networks: 
      - "api.network"

  nginx:
        # specifies the latest nginx image
        image: nginx:latest
        # Connects the conf file of the container to the conf file in our folder
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
        # It will start up the nginx only when all api containers have started
        depends_on: 
            - api
        # Connects the port 80 of the nginx container to localhost:80 or localhost
        ports: 
            - "23452:23452"
        networks: 
            - "api.network"

networks: 
    api.network: